modLoader="kotlinforforge" #mandatory
loaderVersion="${loader_version_range}" #mandatory
license="${mod_license}"
issueTrackerURL="https://github.com/ZhuRuoLing/AppliedWebTerminal/issues"

[[mods]] #mandatory
modId="${mod_id}" #mandatory
version="${mod_version}" #mandatory
displayName="${mod_name}" #mandatory

# A URL to query for updates for this mod. See the JSON update specification https://docs.neoforged.net/docs/misc/updatechecker/
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional

displayURL="https://github.com/ZhuRuoLing/AppliedWebTerminal"

# A file name (in the root of the mod JAR) containing a logo for display
logoFile="icon.png" #optional

# A text field displayed in the mod UI
#credits="" #optional

authors="${mod_authors}" #optional

description='''${mod_description}'''

[[dependencies.${mod_id}]]
    modId="forge" #mandatory
    mandatory=true #mandatory
    # Optional field describing why the dependency is required or why it is incompatible
    # reason="..."
    versionRange="${forge_version_range}" #mandatory
    # An ordering relationship for the dependency.
    # BEFORE - This mod is loaded BEFORE the dependency
    # AFTER - This mod is loaded AFTER the dependency
    ordering="NONE"
    # Side this dependency is applied on - BOTH, CLIENT, or SERVER
    side="BOTH"

# Here's another dependency
[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="ae2"
    mandatory=true
    versionRange="[15.3.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="configuration"
    mandatory=true
    versionRange="[3.1.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="kotlinforforge"
    mandatory=true
    versionRange="${loader_version_range}"
    ordering="NONE"
    side="BOTH"

# Features are specific properties of the game environment, that you may want to declare you require. This example declares
# that your mod requires GL version 3.2 or higher. Other features will be added. They are side aware so declaring this won't
# stop your mod loading on the server for example.
#[features.${mod_id}]
#openGLVersion="[3.2,)"
